version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-autoContrato
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: autoContrato
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - library-network

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: autoContrato
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/autoContrato
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - db
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  postgres-data: